### ISSUE TITLE
The $String = String is unnecessary 

### ISSUE THREAD

**Issue by louisbuchbinder** [WebReflection/circular-json#33]
Hi I am really happy to have found this module. The next best option is [cycle.js](https://github.com/dscape/cycle) which is using `eval`... 

But I have a question/comment on the code. Please direct your attention to https://github.com/WebReflection/circular-json/blob/master/src/circular-json.js#L20-L22 and https://github.com/WebReflection/circular-json/blob/master/src/circular-json.js#L97-L100

It seems the assignment of `String` to `$String` is a bit awkward, as referenced by the comment. Then the only usage is L99 and L131. L131 can be replaced with `String` directly and L99 is not necessary because `value.slice(1)` creates a new string anyway because strings are literals in js. 

Hope this helps. Not an issue per se, but was definitely a stumbling point for me when reading the code.

**Comment by WebReflection** [comment]
You didn't read that comment, did you? [This line](https://github.com/WebReflection/circular-json/blob/master/src/circular-json.js#L99) cannot be replaced with `String` because some linter might complain, as specified in the comment.

> // there's no way to drop warnings in JSHint
> // about new String ... well, I need that here!
> // faked, and happy linter!

I am using `new $String` because **I need to do so** in order to make this whole module work so ... really, there's nothing to change here.

This module has 7 million downloads per month and it's 100% code covered. I wouldn't waste much time trying to change its aesthetics.

**Comment by louisbuchbinder** [comment]
I am not convinced that it is necessary, however based on how strong your reply was I will back off. I was trying to be helpful and provide feedback. I hope you have a good day. :)

**Comment by WebReflection** [comment]
which part is not convincing?

  * I **need** to use `new String` because the whole logic is based on discriminating between regular JSON strings and special cases solved by this project
  * I **don't want** linters to throw errors if I use `new String` hence **I need** to use an alias to fool linters

Regardless, there is no bug whatsoever here, it's just you probably not understanding why instances of strings are needed.

**Comment by WebReflection** [comment]
This is how this module works: https://github.com/WebReflection/circular-json/blob/master/build/circular-json.max.js#L149-L176

`new String` aliased as `new $String` to avoid linters complaining is not going away any time soon.

**Comment by louisbuchbinder** [comment]
Okay thank you I would appreciate the education if you are willing. It is my understanding that strings are literal in js. So 
```
var a = 'mystring';
var b = a.slice(1);
// a is 'mystring'
// b is a new string 'ystring'
```
so there is no need for the `new String(a.slice(1))`

But maybe with special chars it's different? Is that your point.

**Comment by louisbuchbinder** [comment]
Also definitely not a bug. I apologize if opening this in the issues was the wrong place. I just wanted to start a thread.

**Comment by WebReflection** [comment]
You are missing the reason I need instances of strings. I really apologies but I don't have time for this.

**Comment by louisbuchbinder** [comment]
Thanks for your time then

**Comment by WebReflection** [comment]
I mean ... just fork this repo, apply your changes, and see tests failing. Start from there to understand why I use instances of Strings that are not the equivalent of strings.

`"blah" instanceof String` is false ... I don't want `typeof` strings there, those are useless to this module, I need to figure out instances to easily/quickly/robustly find out recursions instead of just regular strings.

**Comment by louisbuchbinder** [comment]
yes I am playing with exactly that now

**Comment by WebReflection** [comment]
this is to distinguish later on while recreating the recursive structure:
https://github.com/WebReflection/circular-json/blob/master/src/circular-json.js#L97-L100

if you'll ever find a better way to do that I'll listen. If you tell me, after 18 years of writing JS, contributing to its specifications, and writing books about it, that a string in JS is a string, I'm afraid I can't explain much more 'cause I don't have time.

Have a nice learning.

**Comment by WebReflection** [comment]
P.S. it's also 1am here so apologies I'm also tired

**Comment by louisbuchbinder** [comment]
Well thanks for responding so quickly.
