### ISSUE TITLE
Is circular-json suitable for websocket instances?

### ISSUE THREAD

**Issue by Globik** [WebReflection/circular-json#34]
Let's say we have websocket websocket.on('connection', ws=> bla bla the code ...
Is it possible to serialize ws instance with circular-json? And after deserialization will be ws instance usable?
ws is a nested object with lot of functions and events.

**Comment by WebReflection** [comment]
you need to answer these two questions first:

  * does a websocket contains circular references?
  * if previous answer is yes, is a websocket serializable as JSON?

But since you asked about this later on

>  after deserialization will be ws instance usable?

I guess you need to understand what is JSON about, and how it works.

It's not an equivalent of php serialize/unserialize, it represents 4 primitives (string, number, boolean, null) and 2 data structures (objects with string-key/json-value pairs or arrays of json values).

You can, however, use its extra utilities to create your own revival logic and generate new instances while deserializing (assuming you have also a logic to serialize them).

**Comment by Globik** [comment]
I don't know. Not on comp yet. Just thought about this. A little experiment. If one could complex nested objects to save into any database. And then reuse all that stuff.

**Comment by WebReflection** [comment]
You need a mechanism to serialize the instance class, which has to be reachable through a global scope, and deserialize it keeping its state preserved so that all internals should be exposed or JSON will miss that.

This is a different issue than circular references, which is the only thing that CircularJSON solves.
