### ISSUE TITLE
Enhancement: accept a parser function as a third argument of CircularJSON.parse

### ISSUE THREAD

**Issue by David-Desmaisons** [WebReflection/circular-json#39]
The idea is to add a new argument to the parser API:

```Javascript
CircularJSON.parse(string, reviver, parser)
```
If specified this parser function will be used instead of `JSON.parse` during parsing.
This will make possible to use none standard parser with circular capabilty such as [JSON-js](https://github.com/douglascrockford/JSON-js) or [JSON.parseMore](https://github.com/Canop/JSON.parseMore).

Please tell me if you are Ok with such an enhancement, if so I can create a PR.

**Comment by WebReflection** [comment]
I'm not sure I understand what's the goal, or the advantage, of this proposal:

  * this module works **very well** with the way JSON works and I don't want to maintain random parsers
  * you can use the reviver already to do what you want with values while these are being parsed

can you please elaborate a bit more?

**Comment by David-Desmaisons** [comment]
* The use case:
I need to handle not only circular references but also `NaN` and `Infinity` parsing which are not part of JSON specification. On the other hand `JSON.parseMore` handles such use case.

* using reviver:
This will not work as `JSON.parse('{"v":NaN}'), reviver` will rise an exception before calling the reviver, because the original string is not a valid JSON.

* The current hack:
```
    var originalParser = JSON.parse;
    JSON.parse = parseMore;
    var res = updateVm(CircularJson.parse(rawVm));
    JSON.parse = originalParser;
```
This, though ugly, will give me a parser with both NaN, Inifinity nad circular reference capability.

**Comment by WebReflection** [comment]
I don't understand ... if you parse circular references, these must have been produced with `CircularJSON`, right? Since `CircularJSON.stringify` would not produce `NaN` or `Infinity` results, this proposal seems a half backed, disaster prone, because it introduce a way out but not a way in, and I'v eno idea why you're parsing JSON that is not JSON with this module ... you shouldn't, it's not encouraged.

**However**, using a different parser than `JSON` itself looks like a reasonable requirement.

How about exposing a `parser` property instead that would point to `JSON` object but could be replaced with anything that simulate the exact same API that JSON has ?

**Comment by David-Desmaisons** [comment]
I got your point: in fact I am generating circular JSON from C# code in [Neutronium](https://github.com/NeutroniumCore/Neutronium). This data is then read on the javascript side using `CircularJSON.parse`. So as I have the full hability to produce `Nan` and `Infinity` output, the idea is to get back this values on the javascript side: https://github.com/NeutroniumCore/neutronium-vue/issues/4

Regarding your second point, this proposal will be perfect for my use case. Tell if it is ok if I submit a PR with this changes.

**Comment by David-Desmaisons** [comment]
Thanks @WebReflection for the discussion and the very quick enhacement. Work like a charm!
